//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentDetail
    {
        public int id { get; set; }
        public Nullable<int> Patientid { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> NurseId { get; set; }
        public Nullable<int> DignosisId { get; set; }
        public Nullable<int> Prescription { get; set; }
        public decimal TreatmentFee { get; set; }
        public Nullable<System.DateTime> DOT { get; set; }
        public string Instruction { get; set; }
    
        public virtual Diagnosi Diagnosi { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
